### ISSUE TITLE
Increase button not working for Homematic device

### ISSUE THREAD

**Issue by flosen1304** [nervetattoo/simple-thermostat#195] opened 2020-12-15 08:53 UTC
Hi,
I've got the problem that I can't increase the temperature with the button for a Homematic IP thermostat. If I click on the increase icon this is the result (for step size 0.5):

![grafik](https://user-images.githubusercontent.com/75736446/102192322-e9a9f180-3eba-11eb-87ca-becaf56e7ed4.png)

For step size 1 nothing happens.

Decrease works as ecpected.

```
type: 'custom:simple-thermostat'
entity: climate.hmip_etrv_2_helge
name: Helge
icon: 'hass:thermostat'
decimals: '1'
label:
  temperature: Temperatur
step_layout: column
step_size: '1'

```

Thanks Florian

**Comment by julianess** [comment] 2020-12-15 17:42
I have the same issue with the latest version of the card but with TuYa device thermostat (TS_0601). Decresing seems to work fine but increasing results in string addition instead of numerical addition. I've observed that increasing and decreasing from the details page of the card is working fine instead (is this a different increasing / decreasing mechanism?)

Because 180 degree cannot be set it is marked as red and further increasing / decreasing results in an error: 
<img width="738" alt="Bildschirmfoto 2020-12-15 um 18 20 17" src="https://user-images.githubusercontent.com/9079614/102250755-39f97180-3f04-11eb-80bc-3c072009640e.png">

<img width="326" alt="Bildschirmfoto 2020-12-15 um 18 38 52" src="https://user-images.githubusercontent.com/9079614/102251232-d3c11e80-3f04-11eb-9533-ca3ff1ebc71f.png">

NaN is displayed in this case. I've already tried to workaround this with templating the state value {{ value_json.current_heating_setpoint | float }} as float but didn't work for all cases. Please convert all incoming and outgoing values to a float just to be sure it can be rendered.

**Comment by nervetattoo** [comment] 2020-12-15 18:17
Weird how it happens for only a few. But I do see how the code would make this technically possible after some recent change. Will have to investigate how to best fix that possibility

**Comment by borahshadow** [comment] 2020-12-16 04:55
I have the same issue on mine when the step size is set to 1. If the step size is default (0.5) it works fine. But when I set it to 1 it does as julianess stated and adds a 1 to the end of the temperature. For example, if my temperature was set to 68F I can decrease it and it goes to 67 as expected, but trying to increase it it goes to 671 degrees.

**Comment by lijnkampioen** [comment] 2020-12-17 08:34
In my setup I have to remove the step size completely. Sometimes it goes from 20 to 210 degrees, other times i get the NaN issue.
Hopefully you can solve this. This is the best thermostat card available

**Comment by flosen1304** [comment] 2020-12-17 09:25
> 
> 
> In my setup I have to remove the step size completely. Sometimes it goes from 20 to 210 degrees, other times i get the NaN issue.
> Hopefully you can solve this. This is the best thermostat card available

Yes, thi works for me, too! It usees 0.5 as step size which is the size defined in climate entity.
So I can finally use this great card! Thnaks

**Comment by Muzza** [comment] 2020-12-22 03:57
I get the same with Sensibo thermostats. They don't support half degree increases so I can't just remove the step size. If I set the step size to 1 it jumps from 20 degrees to 201 degrees when going up. Decreasing the temperature works fine.

**Comment by msholsve** [comment] 2020-12-28 11:50
@Muzza, I think the issue is that the visual editor sets the step size to be a string and not a float. 

Try going into the code editor and remove the quotation marks around 0.5, like this:
`step_size: '0.5'` -> `step_size: 0.5`

Hopefully this resolves your issue and everybody else's issue

**Comment by mikedrawback** [comment] 2020-12-29 01:56
@msholsve I have this issue also and I can confirm changing the value to a float instead of a string in the code editor fixes it.

**Comment by JCandle** [comment] 2020-12-29 20:42
Confirmed, changing the step size fixed this issue.

from:
    step_size: '1'
to
    step_size: 1

**Closed** 2020-12-29 21:55 UTC
Labels: bug
