### ISSUE TITLE
[FEATURE REQUEST] Custom temp settings

### ISSUE THREAD

**Issue by banolka** [nervetattoo/simple-thermostat#42] opened 2019-03-26 14:11 UTC
Will it be possible to have ability to add 1 button temp. selection? 

example: I want to set my heater to specific temperature lets say 30C I have my thermostat currently set to 16C I have 1 button which I click and settings is changed to 30C

**Comment by nervetattoo** [comment] 2019-03-27 10:57
This is a duplicate of #2 which I originally aimed to do from the very start but never prioritised

**Closed by nervetattoo** 2019-03-27 10:57 UTC
Labels: duplicate
