### ISSUE TITLE
Not working after 0.88.0 upgrade

### ISSUE THREAD

**Issue by ltjessem** [nervetattoo/simple-thermostat#27] opened 2019-02-21 07:33 UTC
`2019-02-21 08:29:59 ERROR (MainThread) [frontend.js.latest.201902200] http://192.168.1.135:8123/local/simple-thermostat/simple-thermostat.js?v=1:5:10 Uncaught TypeError: Cannot convert undefined or null to object`

**Comment by nervetattoo** [comment] 2019-02-21 09:18
I know there is an issue with HA replacing a certain button component that the card relied on. I've yet to upgrade myself so I can't fully say if this is the only breaking thing. (zwave stack takes so long to initiate that I try to time upgrades for when I don't need to interact with anything for a long time 😸 ) 

I have a fix for this in the works that I'll publish very very soon, hope you can verify back after that if it works?

**Comment by ltjessem** [comment] 2019-02-21 09:40
Will do!

**Comment by nervetattoo** [comment] 2019-02-21 11:08
https://github.com/nervetattoo/simple-thermostat/releases/tag/0.18.0

**Comment by ltjessem** [comment] 2019-02-21 11:23
Still seeing the same error unfortunately

**Comment by nervetattoo** [comment] 2019-02-21 11:35
Alright, I'll get back to this once I've upgraded myself :)

**Comment by JumpMaster** [comment] 2019-02-21 13:55
0.18.0 has fixed the issues for me.  It's working well again.

**Comment by ltjessem** [comment] 2019-02-21 16:19
My bad, I finally got it working again. Only way I could get it working again was to remove the .js, restart, then add the .js again. Odd, but solved.

**Comment by nervetattoo** [comment] 2019-02-21 19:20
Good, I was unable to reproduce with 0.18 as well. Closing this.
You probably got a cached version in your browser though @ltjessem, did you bump the number in `v=1` in the resources section when you initially attempted to upgrade?

**Closed by nervetattoo** 2019-02-21 19:20 UTC
Labels: bug

**Comment by ltjessem** [comment] 2019-02-22 09:05
I didn't touch the version number, but it was definitely a caching issue. Thanks for resolving this so quickly!
