### ISSUE TITLE
UI Editor Not working any more

### ISSUE THREAD

**Issue by KNXBroker** [nervetattoo/simple-thermostat#233] opened 2021-04-08 04:14 UTC
Hello, since 2.0.0 the ui editor is not working anymore. Changes are not stored.  Configuration can only be done via YAML.

I'm wondering why this issue has not already been posted, did I oversee any note / comment / hint? 

Thank you, great card. 

![Screenshot_20210408-060532](https://user-images.githubusercontent.com/25910703/113967153-b657ed80-9830-11eb-9357-6d19e0a99cb3.png)

**Comment by KNXBroker** [comment] 2021-04-08 17:57
I have some additional information: Changing things in YAML mode or shown in UI editor when switching back to UI editor, but not the other way round: Changing things in UI editor or not shown in YAML mode. 

Furthermore I have recognized that the card configuration does not show "SAVE" when changing things in UI editor only.

**Comment by KNXBroker** [comment] 2021-04-08 18:51
And again some information: Just saw that there are some strange errers in the logs . Don't know if this is linked to the problem.

```
Logger: frontend.js.latest.202104071
Source: components/system_log/__init__.py:190
First occurred: 20:46:48 (9 occurrences)
Last logged: 20:48:45

http://192.168.178.xx:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:18684 Uncaught TypeError: Cannot assign to read only property 'name' of object '#<Object>'
http://192.168.178.xx:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:18684 Uncaught TypeError: Cannot assign to read only property 'step' of object '#<Object>'
```

**Comment by nervetattoo** [comment] 2021-04-08 20:55
Weird. Can you make sure your browser cache gets cleared? It sounds like you are using a cached old version of the editor. I just tested editing and it worked fine for me.

**Comment by synth3tk** [comment] 2021-04-08 23:44
I'm running into this issue as well. I'm using 2.2.1 which I just upgraded to as part of my troubleshooting, but I had this problem on 2.0.0 as well. I'm on HA 2021.4.0.

```
Logger: frontend.js.latest.202104071
Source: components/system_log/__init__.py:190
First occurred: 6:44:52 PM (149 occurrences)
Last logged: 7:39:30 PM

http://<URL>/hacsfiles/simple-thermostat/simple-thermostat.js:285:18838 TypeError: can't define property "header": Object is not extensible
http://<URL>/hacsfiles/simple-thermostat/simple-thermostat.js:285:18679 TypeError: can't define property "entity": Object is not extensible
http://<URL>/hacsfiles/simple-thermostat/simple-thermostat.js:285:19879 TypeError: "decimals" is read-only
http://<URL>/hacsfiles/simple-thermostat/simple-thermostat.js:285:19879 TypeError: "step_size" is read-only
http://<URL>/hacsfiles/simple-thermostat/simple-thermostat.js:285:19854 TypeError: can't define property "header": Object is not extensible
```

**Comment by nervetattoo** [comment] 2021-04-09 04:34
Do you edit existing cards or add new? Yesterday I tested adding a new card and changing every option in the editor.
Does this error happen when you open the editor, or when you type/edit something? Click on something?
Did you try to manually clear your browser cache?

**Comment by KNXBroker** [comment] 2021-04-09 04:35
Just updated to 2.2.1, issue is still there. I have already cleared the cache of my PC, it was the first thing I have tried. Today I even have reinstalled Home assistant App, issue is still there :-(

**Comment by KNXBroker** [comment] 2021-04-09 04:52
Modifing or creating a new card doesn't matter. The only steps I have done with a new card:
Add Card --> Select simple thermostat --> select entity --> save

Result: 

```
You need to define an entity
type: 'custom:simple-thermostat'
```

Strange....

**Comment by nervetattoo** [comment] 2021-04-09 06:54
Weeeeird. And when you open that config, try to view it as yaml, how does it look?
Do you do this in the HA App or in a browser?

**Comment by KNXBroker** [comment] 2021-04-09 17:39
Here is the result of the steps described above:

`type: 'custom:simple-thermostat'`

I have written some text in every UI editor field --> same behaviour. 
I have uninstalled and reinstalled the component --> some behaviour.

Here a new log:

```
http://192.168.178.xx:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:19867 Uncaught TypeError: Cannot add property header, object is not extensible
http://192.168.178.xx:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:19886 Uncaught TypeError: Cannot add property fallback, object is not extensible
http://192.168.178.xx:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:19886 Uncaught TypeError: Cannot add property decimals, object is not extensible
http://192.168.178.xx:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:19886 Uncaught TypeError: Cannot add property step_size, object is not extensible
http://192.168.178.xx:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:19886 Uncaught TypeError: Cannot add property unit, object is not extensible
```

**Comment by nervetattoo** [comment] 2021-04-09 20:59
So you are editing using the Android mobile app, or?
What device?
Unless someone else pipes in with the same issue I figure this might be down to the HA App / device type. Its possible that its down to a difference in the JS runtime in the browser you are using.
Do you see the same error on mobile and on a computer?

**Comment by synth3tk** [comment] 2021-04-09 21:03
I was seeing this issue in Firefox.

**Comment by KNXBroker** [comment] 2021-04-10 04:56
Could it be a language issue? I'm German
I have switched HASS language to English, but this did not help.
I have the issue on my pc and on my android phone. 

On the pc error is always the same:

New card on windows 10 with Microsoft Edge Version 89.0.774.75 (Offizielles Build) (64-Bit)

```
Logger: frontend.js.latest.202104072
Source: components/system_log/__init__.py:190
First occurred: 6:48:16 (1 occurrences)
Last logged: 6:48:16

http://192.168.178.xx:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:19886 Uncaught TypeError: Cannot add property entity, object is not extensible
```

New card on windows 10 with   Google Chrome Version 89.0.4389.114 (Offizieller Build) (64-Bit)

```
Logger: frontend.js.latest.202104072
Source: components/system_log/__init__.py:190
First occurred: 6:51:49 (1 occurrences)
Last logged: 6:51:49

http://192.168.178.xx:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:19886 Uncaught TypeError: Cannot add property entity, object is not extensible
```

**Comment by nervetattoo** [comment] 2021-04-10 19:18
Starting in [v2.2.2](https://github.com/nervetattoo/simple-thermostat/releases/tag/v2.2.2) I also publish a `simple-thermostat.debug.js` that is not minified. That means the error code will point to a line number that is more readable, and might be a pointer as to where the error actually happens.

Unfortunately you need to manually download and overwrite the file with this debug file to install it. Could you test it and see what line number it errs on?

**Comment by KNXBroker** [comment] 2021-04-10 19:53
I'm not sure if I understood it correct, I have: 

- installed V2.2.2
- deleted /config/www/community/simple-thermostat/simple-thermostat.js
- deleted /config/www/community/simple-thermostat/simple-thermostat.js.gz
- renamed simple-thermostat.debug.js to simple-thermostat.js
- renamed simple-thermostat.debug.js.gz to simple-thermostat.js
- Cleared cache browser

Result after creating a new card with entity only:

```
Logger: frontend.js.latest.202104073
Source: components/system_log/__init__.py:190
First occurred: 21:51:50 (1 occurrences)
Last logged: 21:51:50

http://192.168.178.xx:8123/hacsfiles/simple-thermostat/simple-thermostat.js:2818:13 Uncaught TypeError: Cannot add property entity, object is not extensible


```

**Comment by nervetattoo** [comment] 2021-04-10 20:11
You understood perfectly 👍 
Now I at least know exactly where the error happens in the code.

**Comment by D0m3L** [comment] 2021-04-11 12:29
Same problem for me. Using v2.2.0
Moreover toggle entity seems to stop working for me as well. This is what I got on the web console when I trigger the toggle button:

`app.ebe75b7a.js:12795 
Uncaught (in promise) TypeError: e.indexOf is not a function
    at i (app.ebe75b7a.js:12795)
    at HTMLElement.value (chunk.1f510d4b62a23dbb7a38.js:1971)
    at HTMLElement.update (app.ebe75b7a.js:12795)
    at HTMLElement.performUpdate (app.ebe75b7a.js:12795)
    at HTMLElement._enqueueUpdate (app.ebe75b7a.js:12795)`

**Comment by KNXBroker** [comment] 2021-04-12 16:02
Issue still there with V2.2.3 :-(

For your information, I'm using HASS on the following:

```
Home Assistant OS 5.13 64 Bit version
Supervisor-2021.03.9
Docker-Version 19.03.15
Board rpi4
```

I have tested the card on a friend's installation (same hardware / installation): same issue.
@synth3tk: Which hardware / installation method are you using? Same / similar?

Furthermore I have reflashed my card today: same issue

**Comment by synth3tk** [comment] 2021-04-12 16:23
2.3.1 didn't solve it for me as well. Still getting the same read-only and "not extensible" errors.

```
Home Assistant OS 5.13
supervisor-2021.03.9
core-2021.4.1
```

Running as a VM in Proxmox.

**Comment by nervetattoo** [comment] 2021-04-13 18:50
I did remove some errors I finally managed to reproduce in Chrome myself. Curious to hear if this helps your cases

**Comment by synth3tk** [comment] 2021-04-13 19:05
Same errors on 2.3.2. Tried both editing the existing card and adding a new card.
![image](https://user-images.githubusercontent.com/2099988/114606720-a04f9000-9c69-11eb-8a74-f4a1473d891c.png)

**Comment by nervetattoo** [comment] 2021-04-13 19:06
Yeah, expected as much. I can't for the life of me reproduce that error :rage4:

**Comment by KNXBroker** [comment] 2021-04-13 19:07
Unforntunately V2.3.2 did neither fix the issue for me 😢

**Comment by synth3tk** [comment] 2021-04-13 19:35
Ok, update: I can now make changes in the YAML that are accurately reflected. So it appears you solved part of it, but the UI configuration is still broken.

**Comment by bsp9493** [comment] 2021-04-25 17:18
same issue for me, plus one other

I have a toggle_entity defined.  this would normally place a small switch in the top right corner of my card.  this is NOT being displayed.

`toggle_entity:
  entity_id: switch.pentair_ec_60_dd_pool
  name: master

thanx in advance

**Comment by bsp9493** [comment] 2021-04-25 17:22
one addition if it helps... just noticed this in my logs

`Logger: frontend.js.latest.202104073
Source: components/system_log/__init__.py:190 
First occurred: 10:06:51 AM (26 occurrences) 
Last logged: 10:13:15 AM

http://homeassistant.local:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:61511 TypeError: Attempted to assign to readonly property.
http://homeassistant.local:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:61495 TypeError: Attempted to assign to readonly property.
http://homeassistant.local:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:61570 TypeError: Attempted to assign to readonly property.
http://homeassistant.local:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:61554 TypeError: Attempted to assign to readonly property.`

**Comment by nervetattoo** [comment] 2021-05-02 19:29
I've still not been able to reproduce this bug myself, which is highly frustrating. But, I did notice that the same problem have been reported across multiple other cards historically so there might be something related to how the card edit UI works in HA I need to look into. Only half of the editor comes from code in the custom card, the rest is built into HA.

Anyways, I'm still investigating this issue from time to time and do intend to get it fixed eventually.
Feel free to keep reporting new incidents 👍

**Comment by synth3tk** [comment] 2021-05-03 01:49
No worries, take your time!

**Comment by Lopton** [comment] 2021-05-09 00:20
Fresh install here and I get the following error in my Home Assistant Logs:
"https://192.168.4.13:8123/hacsfiles/simple-thermostat/simple-thermostat.js:285:33489 TypeError: can't define property "entity": Object is not extensible" 

And this is what it looks like in the UI:
![image](https://user-images.githubusercontent.com/6832191/117556796-9a0ec280-b021-11eb-9e5f-5c706494815f.png)

**Comment by stefangehn** [comment] 2021-05-11 17:05
After a bit of digging it looks like commit `7f66a551f67ce85e02130f127ead8488a1e5fa58` changed the way adding properties to `this.config` in the editor is done. The old code reassigned the config object, extending it with the new property, i.e. `this.config = { ...this.config, [key]: value }`. The new `setValue()` function rather uses `o[key] = value` which does not appear to workand leads to the "cannot be extended" error message.

Since setValue supports nested config options while the old code only supported flat properties on the config object and my JS is still rather limited I'm a bit at a loss how a proper fix could look like. But maybe this provides a starting point of how to tackle this.

**Comment by nervetattoo** [comment] 2021-05-11 18:38
Thanks for digging in @stefangehn 
You are probably onto something. The `setConfig` method is called from HA, and its not impossible that a frozen object is passed. I'll try to spread the existing config to a new object and you can test if that helps.

**Comment by stefangehn** [comment] 2021-05-12 19:02
The fix works for toplevel properties like `entity` but still fails for sub-properties like `layout.mode.names`. The reason is indeed that `setConfig` is called with a frozen object. I suspect this is the case since https://github.com/home-assistant/frontend/pull/4862 got merged. For flat config objects the suggested code indeed works:
```js
this.config = { ...config }
```

However since simple-thermostat uses nested config entries it needs some sort of deep-clone implementation for the setConfig code, otherwise all the sub-objects will still be frozen. Afterwards the remaining code does not appear to need any of the previous workarounds anymore, i.e. `this.config` can be modified at will again.

FWIW, I partially got the card working with this:

```js
  setConfig(config: CardConfig): void {
    this.config = {
      ...config,
      header: {
        ...config?.header,
      },
      layout: {
        ...config?.layout,
        mode: {
          ...config?.layout?.mode,
        },
        sensors: {
          ...config?.layout?.sensors,
        },
      },
      hide: {
        ...config?.hide,
      },
      label: {
        ...config?.label,
      },
    }
  }
```

Mind you, this will create all the sub-sections like `layout` etc. which is obviously undesired. The suggested https://github.com/balloob/deep-clone-simple module seems to lack a TS support (i.e. it'd need a `index.d.ts` with appropriate type information to pull it into `editor.ts.

**Comment by nervetattoo** [comment] 2021-05-12 21:34
Hooray! That was the confirmation I'd hoped for.  Thanks a bunch for digging into this 💯 ! I'll make sure it just makes a copy in the recursive setvalue func. Should probably find time to do this in a few days

**Closed** 2021-05-21 08:47 UTC
Labels: bug

**Comment by nervetattoo** [comment] 2021-05-21 08:50
LMK how it goes 🤞

**Comment by KNXBroker** [comment] 2021-05-26 05:06
Seems to Work! Thank you
