### ISSUE TITLE
2.3.1 breaks UI functionality

### ISSUE THREAD

**Issue by platinumseo** [nervetattoo/simple-thermostat#248] opened 2021-04-12 09:18 UTC
Just updated to 2.3.1 today and noticed I was suddenly unable to save any changes made in either the UI or YAML. Looking at the logs it is filled with the below:

2021-04-12 04:10:02 ERROR (MainThread) [frontend.js.latest.202104073] http://nabu.casalink/hacsfiles/simple-thermostat/simple-thermostat.js:285:48163 TypeError: Attempted to assign to readonly property.

Lost count as to how many of those errors there were.

**Comment by synth3tk** [comment] 2021-04-12 16:25
There's similar conversations in #233.

**Comment by nervetattoo** [comment] 2021-04-12 19:45
Closing as duplicate of #233

**Closed by nervetattoo** 2021-04-12 19:45 UTC
